// AUTO-GENERATED by scripts/generate-soundfont-manifest.mjs — do not edit by hand.
// Regenerate with: npm run soundfonts:manifest

/** A single SoundFont bank available in `public/assets/soundfonts`. */
export interface SoundfontEntry {
  /** Stable identifier, e.g. `"keyboards/concert-grand"`. */
  id: string;
  /** Display name taken from the filename. */
  name: string;
  /** Slugified family folder, e.g. `"synth-pads"`. */
  family: string;
  /** Human-readable family label for UI grouping. */
  familyLabel: string;
  /** Public URL, percent-encoded and safe to pass to `fetch`. */
  url: string;
  /** Container format. SF3 stores Vorbis-compressed samples. */
  format: "sf2" | "sf3";
  /** File size in bytes, used to show download progress. */
  bytes: number;
}

export const SOUNDFONTS: readonly SoundfontEntry[] = [
  {
    "id": "keyboards/bright-grand",
    "name": "Bright Grand",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Bright%20Grand.sf3",
    "format": "sf3",
    "bytes": 10278962
  },
  {
    "id": "keyboards/concert-grand",
    "name": "Concert Grand",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Concert%20Grand.sf3",
    "format": "sf3",
    "bytes": 10350506
  },
  {
    "id": "keyboards/cutter-clavi",
    "name": "Cutter Clavi",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Cutter%20Clavi.sf3",
    "format": "sf3",
    "bytes": 486540
  },
  {
    "id": "keyboards/drawbar-organ",
    "name": "Drawbar Organ",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Drawbar%20Organ.sf2",
    "format": "sf2",
    "bytes": 2168258
  },
  {
    "id": "keyboards/e-piano-fm",
    "name": "E.Piano FM",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/E.Piano%20FM.sf3",
    "format": "sf3",
    "bytes": 461834
  },
  {
    "id": "keyboards/e-piano-rhodes",
    "name": "E.Piano Rhodes",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/E.Piano%20Rhodes.sf3",
    "format": "sf3",
    "bytes": 1374378
  },
  {
    "id": "keyboards/harpsichord",
    "name": "Harpsichord",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Harpsichord.sf2",
    "format": "sf2",
    "bytes": 2694336
  },
  {
    "id": "keyboards/honky-tonk",
    "name": "Honky Tonk",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Honky%20Tonk.sf3",
    "format": "sf3",
    "bytes": 9652760
  },
  {
    "id": "keyboards/percussive-organ",
    "name": "Percussive Organ",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Percussive%20Organ.sf2",
    "format": "sf2",
    "bytes": 1973522
  }
] as const;

/** Total size of the bundled soundfont library, in bytes. */
export const SOUNDFONT_LIBRARY_BYTES = 39441096;

/** The bank loaded on first paint — a full concert grand piano. */
export const DEFAULT_SOUNDFONT_ID = "keyboards/concert-grand";

/** Fast id -> entry lookup for the audio engine. */
export const SOUNDFONT_BY_ID: ReadonlyMap<string, SoundfontEntry> = new Map(
  SOUNDFONTS.map((entry) => [entry.id, entry]),
);

/** Families in display order, each with its member banks. */
export function groupSoundfontsByFamily(): {
  family: string;
  label: string;
  entries: SoundfontEntry[];
}[] {
  const groups = new Map<string, { family: string; label: string; entries: SoundfontEntry[] }>();

  for (const entry of SOUNDFONTS) {
    let group = groups.get(entry.family);
    if (!group) {
      group = { family: entry.family, label: entry.familyLabel, entries: [] };
      groups.set(entry.family, group);
    }
    group.entries.push(entry);
  }

  return [...groups.values()];
}
