// AUTO-GENERATED by scripts/generate-soundfont-manifest.mjs — do not edit by hand.
// Regenerate with: npm run soundfonts:manifest

/** A single SoundFont bank available in `public/assets/soundfonts`. */
export interface SoundfontEntry {
  /** Stable identifier, e.g. `"keyboards/concert-grand"`. */
  id: string;
  /** Display name taken from the filename. */
  name: string;
  /** Slugified family folder, e.g. `"synth-pads"`. */
  family: string;
  /** Human-readable family label for UI grouping. */
  familyLabel: string;
  /** Public URL, percent-encoded and safe to pass to `fetch`. */
  url: string;
  /** Container format. SF3 stores Vorbis-compressed samples. */
  format: "sf2" | "sf3";
  /** File size in bytes, used to show download progress. */
  bytes: number;
}

export const SOUNDFONTS: readonly SoundfontEntry[] = [
  {
    "id": "root/applause-fx",
    "name": "Applause FX",
    "family": "root",
    "familyLabel": "Uncategorised",
    "url": "/assets/soundfonts/Applause%20FX.sf2",
    "format": "sf2",
    "bytes": 127202
  },
  {
    "id": "bass/acoustic-bass",
    "name": "Acoustic Bass",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Acoustic%20Bass.sf3",
    "format": "sf3",
    "bytes": 383652
  },
  {
    "id": "bass/finger-bass",
    "name": "Finger Bass",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Finger%20Bass.sf2",
    "format": "sf2",
    "bytes": 1731452
  },
  {
    "id": "bass/picked-bass",
    "name": "Picked Bass",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Picked%20Bass.sf2",
    "format": "sf2",
    "bytes": 3954764
  },
  {
    "id": "bass/slap-bass-2",
    "name": "Slap Bass 2",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Slap%20Bass%202.sf2",
    "format": "sf2",
    "bytes": 4468332
  },
  {
    "id": "bass/synth-bass-1",
    "name": "Synth Bass 1",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Synth%20Bass%201.sf2",
    "format": "sf2",
    "bytes": 313222
  },
  {
    "id": "bass/synth-bass-2",
    "name": "Synth Bass 2",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Synth%20Bass%202.sf3",
    "format": "sf3",
    "bytes": 108106
  },
  {
    "id": "bass/synth-bass-4",
    "name": "Synth Bass 4",
    "family": "bass",
    "familyLabel": "Bass",
    "url": "/assets/soundfonts/bass/Synth%20Bass%204.sf3",
    "format": "sf3",
    "bytes": 29040
  },
  {
    "id": "choirs/choir-aahs",
    "name": "Choir Aahs",
    "family": "choirs",
    "familyLabel": "Choirs",
    "url": "/assets/soundfonts/choirs/Choir%20Aahs.sf2",
    "format": "sf2",
    "bytes": 8119698
  },
  {
    "id": "choirs/choir-oohs",
    "name": "Choir Oohs",
    "family": "choirs",
    "familyLabel": "Choirs",
    "url": "/assets/soundfonts/choirs/Choir%20Oohs.sf2",
    "format": "sf2",
    "bytes": 1245966
  },
  {
    "id": "guitars/banjo",
    "name": "Banjo",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Banjo.sf3",
    "format": "sf3",
    "bytes": 520422
  },
  {
    "id": "guitars/concert-nylon-guitar",
    "name": "Concert Nylon Guitar",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Concert%20Nylon%20Guitar.sf3",
    "format": "sf3",
    "bytes": 1490336
  },
  {
    "id": "guitars/jazz-guitar",
    "name": "Jazz Guitar",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Jazz%20Guitar.sf2",
    "format": "sf2",
    "bytes": 7499316
  },
  {
    "id": "guitars/koto",
    "name": "Koto",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Koto.sf3",
    "format": "sf3",
    "bytes": 406130
  },
  {
    "id": "guitars/overdrive-guitar",
    "name": "Overdrive Guitar",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Overdrive%20Guitar.sf2",
    "format": "sf2",
    "bytes": 3101734
  },
  {
    "id": "guitars/shamisen",
    "name": "Shamisen",
    "family": "guitars",
    "familyLabel": "Guitars & Plucked",
    "url": "/assets/soundfonts/Guitars/Shamisen.sf3",
    "format": "sf3",
    "bytes": 202638
  },
  {
    "id": "keyboards/bright-grand",
    "name": "Bright Grand",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Bright%20Grand.sf3",
    "format": "sf3",
    "bytes": 10278962
  },
  {
    "id": "keyboards/concert-grand",
    "name": "Concert Grand",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Concert%20Grand.sf3",
    "format": "sf3",
    "bytes": 10350506
  },
  {
    "id": "keyboards/cutter-clavi",
    "name": "Cutter Clavi",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Cutter%20Clavi.sf3",
    "format": "sf3",
    "bytes": 486540
  },
  {
    "id": "keyboards/drawbar-organ",
    "name": "Drawbar Organ",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Drawbar%20Organ.sf2",
    "format": "sf2",
    "bytes": 2168258
  },
  {
    "id": "keyboards/e-piano-fm",
    "name": "E.Piano FM",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/E.Piano%20FM.sf3",
    "format": "sf3",
    "bytes": 461834
  },
  {
    "id": "keyboards/e-piano-rhodes",
    "name": "E.Piano Rhodes",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/E.Piano%20Rhodes.sf3",
    "format": "sf3",
    "bytes": 1374378
  },
  {
    "id": "keyboards/harpsichord",
    "name": "Harpsichord",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Harpsichord.sf2",
    "format": "sf2",
    "bytes": 2694336
  },
  {
    "id": "keyboards/honky-tonk",
    "name": "Honky Tonk",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Honky%20Tonk.sf3",
    "format": "sf3",
    "bytes": 9652760
  },
  {
    "id": "keyboards/percussive-organ",
    "name": "Percussive Organ",
    "family": "keyboards",
    "familyLabel": "Keyboards",
    "url": "/assets/soundfonts/keyboards/Percussive%20Organ.sf2",
    "format": "sf2",
    "bytes": 1973522
  },
  {
    "id": "misc/000-002-electric-grand",
    "name": "000_002 Electric Grand",
    "family": "misc",
    "familyLabel": "Miscellaneous",
    "url": "/assets/soundfonts/misc/000_002%20Electric%20Grand.sf3",
    "format": "sf3",
    "bytes": 991622
  },
  {
    "id": "misc/000-003-honky-tonk",
    "name": "000_003 Honky Tonk",
    "family": "misc",
    "familyLabel": "Miscellaneous",
    "url": "/assets/soundfonts/misc/000_003%20Honky%20Tonk.sf3",
    "format": "sf3",
    "bytes": 16925804
  },
  {
    "id": "percussion/agogo",
    "name": "Agogo",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Agogo.sf3",
    "format": "sf3",
    "bytes": 12170
  },
  {
    "id": "percussion/brush-kit",
    "name": "Brush Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Brush%20Kit.sf3",
    "format": "sf3",
    "bytes": 3220788
  },
  {
    "id": "percussion/celesta",
    "name": "Celesta",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Celesta.sf3",
    "format": "sf3",
    "bytes": 25818
  },
  {
    "id": "percussion/dance-kit",
    "name": "Dance Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Dance%20Kit.sf3",
    "format": "sf3",
    "bytes": 4943388
  },
  {
    "id": "percussion/electronic-kit",
    "name": "Electronic Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Electronic%20Kit.sf3",
    "format": "sf3",
    "bytes": 5120378
  },
  {
    "id": "percussion/jazz-kit",
    "name": "Jazz Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Jazz%20Kit.sf3",
    "format": "sf3",
    "bytes": 3142856
  },
  {
    "id": "percussion/kalimba",
    "name": "Kalimba",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Kalimba.sf3",
    "format": "sf3",
    "bytes": 36906
  },
  {
    "id": "percussion/melodic-tom",
    "name": "Melodic Tom",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Melodic%20Tom.sf3",
    "format": "sf3",
    "bytes": 11676
  },
  {
    "id": "percussion/orchestra-kit",
    "name": "Orchestra Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Orchestra%20Kit.sf3",
    "format": "sf3",
    "bytes": 3658866
  },
  {
    "id": "percussion/pop-celesta",
    "name": "Pop Celesta",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Pop%20Celesta.sf3",
    "format": "sf3",
    "bytes": 100454
  },
  {
    "id": "percussion/power-kit",
    "name": "Power Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Power%20Kit.sf3",
    "format": "sf3",
    "bytes": 5682710
  },
  {
    "id": "percussion/room-kit",
    "name": "Room Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Room%20Kit.sf3",
    "format": "sf3",
    "bytes": 3194904
  },
  {
    "id": "percussion/sfx-kit",
    "name": "SFX Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/SFX%20Kit.sf3",
    "format": "sf3",
    "bytes": 417688
  },
  {
    "id": "percussion/soft-marimba",
    "name": "Soft Marimba",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Soft%20Marimba.sf2",
    "format": "sf2",
    "bytes": 805882
  },
  {
    "id": "percussion/standard-drum-kit",
    "name": "Standard Drum Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Standard%20Drum%20Kit.sf3",
    "format": "sf3",
    "bytes": 3919388
  },
  {
    "id": "percussion/steel-drums",
    "name": "Steel Drums",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Steel%20Drums.sf3",
    "format": "sf3",
    "bytes": 52178
  },
  {
    "id": "percussion/taiko",
    "name": "Taiko",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Taiko.sf3",
    "format": "sf3",
    "bytes": 22594
  },
  {
    "id": "percussion/tinkle-bell",
    "name": "Tinkle Bell",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Tinkle%20Bell.sf3",
    "format": "sf3",
    "bytes": 1288642
  },
  {
    "id": "percussion/tr-808-kit",
    "name": "TR-808 Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/TR-808%20Kit.sf3",
    "format": "sf3",
    "bytes": 5162396
  },
  {
    "id": "percussion/tr-909-kit",
    "name": "TR-909 Kit",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/TR-909%20Kit.sf3",
    "format": "sf3",
    "bytes": 4907202
  },
  {
    "id": "percussion/woodblock",
    "name": "Woodblock",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Woodblock.sf3",
    "format": "sf3",
    "bytes": 22194
  },
  {
    "id": "percussion/xylophone",
    "name": "Xylophone",
    "family": "percussion",
    "familyLabel": "Percussion & Mallets",
    "url": "/assets/soundfonts/percussion/Xylophone.sf2",
    "format": "sf2",
    "bytes": 1040878
  },
  {
    "id": "strings/concerto-cello",
    "name": "Concerto Cello",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Concerto%20Cello.sf2",
    "format": "sf2",
    "bytes": 1871436
  },
  {
    "id": "strings/fiddle",
    "name": "Fiddle",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Fiddle.sf3",
    "format": "sf3",
    "bytes": 4140918
  },
  {
    "id": "strings/hybrid-strings",
    "name": "Hybrid Strings",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Hybrid%20Strings.sf3",
    "format": "sf3",
    "bytes": 220594
  },
  {
    "id": "strings/orchesta-hit",
    "name": "Orchesta Hit",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Orchesta%20Hit.sf2",
    "format": "sf2",
    "bytes": 161108
  },
  {
    "id": "strings/pizzicato-strings",
    "name": "Pizzicato Strings",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Pizzicato%20Strings.sf2",
    "format": "sf2",
    "bytes": 933622
  },
  {
    "id": "strings/slow-strings",
    "name": "Slow Strings",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Slow%20Strings.sf3",
    "format": "sf3",
    "bytes": 4953868
  },
  {
    "id": "strings/synth-strings-1",
    "name": "Synth Strings 1",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Synth%20Strings%201.sf3",
    "format": "sf3",
    "bytes": 380978
  },
  {
    "id": "strings/synth-strings-2",
    "name": "Synth Strings 2",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Synth%20Strings%202.sf3",
    "format": "sf3",
    "bytes": 221114
  },
  {
    "id": "strings/tremolo-strings",
    "name": "Tremolo Strings",
    "family": "strings",
    "familyLabel": "Strings",
    "url": "/assets/soundfonts/strings/Tremolo%20Strings.sf3",
    "format": "sf3",
    "bytes": 319132
  },
  {
    "id": "synth-pads/100-brightness",
    "name": "100 Brightness",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/100%20Brightness.sf2",
    "format": "sf2",
    "bytes": 988994
  },
  {
    "id": "synth-pads/crystal",
    "name": "Crystal",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Crystal.sf3",
    "format": "sf3",
    "bytes": 296606
  },
  {
    "id": "synth-pads/metal-pad",
    "name": "Metal Pad",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Metal%20Pad.sf3",
    "format": "sf3",
    "bytes": 1953020
  },
  {
    "id": "synth-pads/polysynth",
    "name": "Polysynth",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Polysynth.sf2",
    "format": "sf2",
    "bytes": 3502446
  },
  {
    "id": "synth-pads/saw-wave-2",
    "name": "Saw Wave 2",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Saw%20Wave%202.sf3",
    "format": "sf3",
    "bytes": 29142
  },
  {
    "id": "synth-pads/saw-wave",
    "name": "Saw Wave",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Saw%20Wave.sf3",
    "format": "sf3",
    "bytes": 674446
  },
  {
    "id": "synth-pads/square-wave-2",
    "name": "Square Wave 2",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Square%20Wave%202.sf3",
    "format": "sf3",
    "bytes": 29106
  },
  {
    "id": "synth-pads/square-wave",
    "name": "Square Wave",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Square%20Wave.sf3",
    "format": "sf3",
    "bytes": 807186
  },
  {
    "id": "synth-pads/sweep-pad",
    "name": "Sweep Pad",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Sweep%20Pad.sf3",
    "format": "sf3",
    "bytes": 220650
  },
  {
    "id": "synth-pads/trance-synth",
    "name": "Trance Synth",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Trance%20Synth.sf3",
    "format": "sf3",
    "bytes": 128342
  },
  {
    "id": "synth-pads/warm-pad",
    "name": "Warm Pad",
    "family": "synth-pads",
    "familyLabel": "Synth & Pads",
    "url": "/assets/soundfonts/synth%20pads/Warm%20Pad.sf3",
    "format": "sf3",
    "bytes": 118410
  },
  {
    "id": "winds/accordeon",
    "name": "Accordeon",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Accordeon.sf2",
    "format": "sf2",
    "bytes": 1712552
  },
  {
    "id": "winds/alto-sax",
    "name": "Alto Sax",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Alto%20Sax.sf2",
    "format": "sf2",
    "bytes": 3703092
  },
  {
    "id": "winds/bagpipe",
    "name": "Bagpipe",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Bagpipe.sf3",
    "format": "sf3",
    "bytes": 258488
  },
  {
    "id": "winds/baritone-sax",
    "name": "Baritone Sax",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Baritone%20Sax.sf2",
    "format": "sf2",
    "bytes": 5982148
  },
  {
    "id": "winds/bassoon",
    "name": "Bassoon",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Bassoon.sf3",
    "format": "sf3",
    "bytes": 520462
  },
  {
    "id": "winds/bottle-blow",
    "name": "Bottle Blow",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Bottle%20Blow.sf3",
    "format": "sf3",
    "bytes": 413962
  },
  {
    "id": "winds/brass",
    "name": "Brass",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Brass.sf2",
    "format": "sf2",
    "bytes": 6744638
  },
  {
    "id": "winds/clarinet",
    "name": "Clarinet",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Clarinet.sf3",
    "format": "sf3",
    "bytes": 643250
  },
  {
    "id": "winds/flute",
    "name": "Flute",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Flute.sf3",
    "format": "sf3",
    "bytes": 843226
  },
  {
    "id": "winds/french-horns",
    "name": "French Horns",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/French%20Horns.sf2",
    "format": "sf2",
    "bytes": 2635970
  },
  {
    "id": "winds/harmonica",
    "name": "Harmonica",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Harmonica.sf3",
    "format": "sf3",
    "bytes": 607286
  },
  {
    "id": "winds/jazz-tenor-sax",
    "name": "Jazz Tenor Sax",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Jazz%20Tenor%20Sax.sf2",
    "format": "sf2",
    "bytes": 7108500
  },
  {
    "id": "winds/muted-trumpet",
    "name": "Muted Trumpet",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Muted%20Trumpet.sf2",
    "format": "sf2",
    "bytes": 1001002
  },
  {
    "id": "winds/ocarina",
    "name": "Ocarina",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Ocarina.sf3",
    "format": "sf3",
    "bytes": 178602
  },
  {
    "id": "winds/pan-flute",
    "name": "Pan Flute",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Pan%20Flute.sf3",
    "format": "sf3",
    "bytes": 305372
  },
  {
    "id": "winds/piccolo",
    "name": "Piccolo",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Piccolo.sf3",
    "format": "sf3",
    "bytes": 767930
  },
  {
    "id": "winds/recorder",
    "name": "Recorder",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Recorder.sf3",
    "format": "sf3",
    "bytes": 226898
  },
  {
    "id": "winds/romantic-trumpet",
    "name": "Romantic Trumpet",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Romantic%20Trumpet.sf3",
    "format": "sf3",
    "bytes": 154734
  },
  {
    "id": "winds/shakuhachi",
    "name": "Shakuhachi",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Shakuhachi.sf3",
    "format": "sf3",
    "bytes": 388642
  },
  {
    "id": "winds/shanai",
    "name": "Shanai",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Shanai.sf3",
    "format": "sf3",
    "bytes": 23638
  },
  {
    "id": "winds/synth-brass-1",
    "name": "Synth Brass 1",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Synth%20Brass%201.sf2",
    "format": "sf2",
    "bytes": 920406
  },
  {
    "id": "winds/trumpet",
    "name": "Trumpet",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Trumpet.sf2",
    "format": "sf2",
    "bytes": 2611482
  },
  {
    "id": "winds/whistle",
    "name": "Whistle",
    "family": "winds",
    "familyLabel": "Winds & Brass",
    "url": "/assets/soundfonts/winds/Whistle.sf3",
    "format": "sf3",
    "bytes": 448726
  }
] as const;

/** Total size of the bundled soundfont library, in bytes. */
export const SOUNDFONT_LIBRARY_BYTES = 198002612;

/** The bank loaded on first paint — a full concert grand piano. */
export const DEFAULT_SOUNDFONT_ID = "keyboards/concert-grand";

/** Fast id -> entry lookup for the audio engine. */
export const SOUNDFONT_BY_ID: ReadonlyMap<string, SoundfontEntry> = new Map(
  SOUNDFONTS.map((entry) => [entry.id, entry]),
);

/** Families in display order, each with its member banks. */
export function groupSoundfontsByFamily(): {
  family: string;
  label: string;
  entries: SoundfontEntry[];
}[] {
  const groups = new Map<string, { family: string; label: string; entries: SoundfontEntry[] }>();

  for (const entry of SOUNDFONTS) {
    let group = groups.get(entry.family);
    if (!group) {
      group = { family: entry.family, label: entry.familyLabel, entries: [] };
      groups.set(entry.family, group);
    }
    group.entries.push(entry);
  }

  return [...groups.values()];
}
